# Generated by Django 5.2.17 on 2026-08-28 14:59

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

CREAR_SECUENCIA_SQL = "CREATE SEQUENCE purchasing_ordendecompra_numero_seq;"
ELIMINAR_SECUENCIA_SQL = "DROP SEQUENCE IF EXISTS purchasing_ordendecompra_numero_seq;"

VINCULAR_SECUENCIA_SQL = (
    "ALTER SEQUENCE purchasing_ordendecompra_numero_seq "
    "OWNED BY purchasing_ordendecompra.numero;"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_producto_stock_minimo_general_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(sql=CREAR_SECUENCIA_SQL, reverse_sql=ELIMINAR_SECUENCIA_SQL),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('purchasing_ordendecompra_numero_seq')", []), editable=False, unique=True)),
                ('deposito_destino', models.CharField(choices=[('general', 'Stock general (obra)'), ('repuestos', 'Stock de repuestos (service)')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='borrador', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='catalog.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-numero'],
                'permissions': [('approve_ordendecompra', 'Puede aprobar o rechazar una orden de compra')],
            },
        ),
        migrations.RunSQL(sql=VINCULAR_SECUENCIA_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='LineaOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_esperado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_orden_compra', to='catalog.productoproveedor')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='purchasing.ordendecompra')),
            ],
            options={
                'verbose_name': 'Línea de orden de compra',
                'verbose_name_plural': 'Líneas de orden de compra',
                'ordering': ['orden_id', 'id'],
            },
        ),
    ]
