# Generated by Django 5.2.17 on 2026-08-25 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_categoria_margen_marca_margen_producto_margen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen_general', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('flete_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo_financiero_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margen_minimo_alerta', models.DecimalField(decimal_places=2, default=15, help_text='Si un descuento deja el margen por debajo de este %, se muestra una alerta (no bloquea).', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuración general de precios',
                'verbose_name_plural': 'Configuración general de precios',
                'permissions': [('manage_margenes', 'Puede configurar márgenes, flete y costo financiero')],
            },
        ),
        migrations.CreateModel(
            name='HistorialCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente_desde', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(default='manual', max_length=50)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_cargados', to=settings.AUTH_USER_MODEL)),
                ('producto_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_costos', to='catalog.productoproveedor')),
            ],
            options={
                'verbose_name': 'Historial de costo',
                'verbose_name_plural': 'Historial de costos',
                'ordering': ['-vigente_desde'],
                'permissions': [('view_precio_repuestos', 'Puede ver precios de productos de la línea de repuestos'), ('manage_costos_repuestos', 'Puede registrar costos nuevos para productos de la línea de repuestos')],
            },
        ),
    ]
