# Generated by Django 5.2.17 on 2026-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_asignar_permisos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='margen_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Margen (%) por defecto para el concepto manual 'Mano de obra' en presupuestos. No es un producto de catálogo, por eso vive acá y no en la jerarquía Producto/Marca/Categoría.", max_digits=5),
        ),
    ]
