# Generated by Django 5.2.17 on 2026-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_configuraciongeneral_margen_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='iva_pct',
            field=models.DecimalField(decimal_places=2, default=21, help_text="Alícuota de IVA (%) para ítems de presupuesto con tipo de IVA '+ IVA'.", max_digits=5),
        ),
    ]
