# Generated by Django 5.2.17 on 2026-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_configuraciongeneral_iva_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='dias_aviso_presupuesto_por_vencer',
            field=models.PositiveIntegerField(default=3, help_text='Días de anticipación a fecha_vencimiento para avisarle al vendedor que un presupuesto Enviado está por vencer (Etapa 9).'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='dias_seguimiento_presupuesto_enviado',
            field=models.PositiveIntegerField(default=3, help_text='Días sin respuesta desde que se envió un presupuesto para que el sistema genere una tarea de seguimiento automática (Etapa 9).'),
        ),
    ]
