# Generated by Django 5.2.17 on 2026-08-30 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_validaciones_numericas'),
        ('pricing', '0007_validaciones_numericas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcosto',
            name='moneda',
            field=models.CharField(choices=[('ars', 'Pesos (ARS)'), ('usd', 'Dólares (USD)')], default='ars', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='historialcosto',
            constraint=models.CheckConstraint(condition=models.Q(('moneda__in', ['ars', 'usd'])), name='historialcosto_moneda_valida'),
        ),
    ]
