# Generated by Django 5.2.17 on 2026-08-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producto_stock_minimo_general_and_more'),
        ('quotes', '0008_itempresupuesto_itempresupuesto_producto_xor_descripcion_manual'),
        ('tasks', '0002_asignar_permisos_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='deposito',
            field=models.CharField(blank=True, choices=[('general', 'Stock general (obra)'), ('repuestos', 'Stock de repuestos (service)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='generada_por',
            field=models.CharField(blank=True, choices=[('seguimiento_presupuesto', 'Seguimiento de presupuesto enviado'), ('presupuesto_por_vencer', 'Presupuesto por vencer'), ('stock_minimo', 'Stock por debajo del mínimo')], default='', help_text='Vacío = la creó una persona. Con valor = generada sola por una de las 3 reglas de la Etapa 9.', max_length=30),
        ),
        migrations.AddField(
            model_name='tarea',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_generadas', to='quotes.presupuesto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_stock_minimo', to='catalog.producto'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generada_por', ''), ('presupuesto__isnull', True), ('producto__isnull', True)), models.Q(('generada_por__in', ['seguimiento_presupuesto', 'presupuesto_por_vencer']), ('presupuesto__isnull', False), ('producto__isnull', True)), models.Q(('generada_por', 'stock_minimo'), ('presupuesto__isnull', True), ('producto__isnull', False)), _connector='OR'), name='tarea_generada_por_coherente_con_campos'),
        ),
    ]
