# Generated by Django 5.2.17 on 2026-08-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0007_asignar_permiso_revertir_aceptado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando_materiales', 'Preparando materiales'), ('listo', 'Listo'), ('en_ejecucion', 'En ejecución'), ('terminado', 'Terminado')], default='pendiente', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_creados', to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trabajo', to='quotes.presupuesto')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-creado_en'],
                'permissions': [('manage_preparacion', 'Puede cambiar el estado de un trabajo a Preparando materiales / Listo'), ('manage_ejecucion_propia', 'Puede cambiar el estado de sus propios trabajos asignados a En ejecución / Terminado')],
            },
        ),
    ]
