# Generated by Django 5.2.17 on 2026-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_asignar_permisos_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando_materiales', 'Preparando materiales'), ('listo', 'Listo'), ('en_ejecucion', 'En ejecución'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30),
        ),
    ]
