# Generated by Django 5.2.17 on 2026-08-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producto_stock_minimo_general_and_more'),
        ('jobs', '0003_alter_trabajo_estado'),
        ('quotes', '0007_asignar_permiso_revertir_aceptado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('duracion_estimada_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_trabajo', to='quotes.seccionpresupuesto')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='jobs.trabajo')),
            ],
            options={
                'verbose_name': 'Etapa de trabajo',
                'verbose_name_plural': 'Etapas de trabajo',
                'ordering': ['trabajo_id', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, help_text='Para un material que todavía no está cargado en el catálogo.', max_length=255)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='jobs.etapatrabajo')),
                ('item_presupuesto_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_trabajo', to='quotes.itempresupuesto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiales_trabajo', to='catalog.producto')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='jobs.trabajo')),
            ],
            options={
                'verbose_name': 'Material de trabajo',
                'verbose_name_plural': 'Materiales de trabajo',
                'ordering': ['trabajo_id', 'etapa_id', 'orden'],
            },
        ),
    ]
