# Generated by Django 5.2.17 on 2026-08-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_producto_stock_minimo_general_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(choices=[('general', 'Stock general (obra)'), ('repuestos', 'Stock de repuestos (service)')], max_length=20)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Con signo: positivo suma stock, negativo resta.', max_digits=12)),
                ('requiere_devolucion', models.BooleanField(default=False, help_text="Solo tiene sentido en una Salida de repuestos: marca que ese material queda 'pendiente de devolución' hasta que se registre qué volvió (regla de negocio 11).")),
                ('referencia_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia_libre', models.CharField(blank=True, help_text='Descripción libre del origen/destino cuando todavía no hay un objeto vinculado.', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='catalog.producto')),
                ('referencia_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
                ('salida_relacionada', models.ForeignKey(blank=True, help_text='Solo se completa en una Devolución: la Salida de repuestos que resuelve.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='stock.movimientostock')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-creado_en'],
                'permissions': [('manage_stock_general', 'Puede registrar entradas y salidas en el stock general (obra)'), ('ajustar_stock_general', 'Puede hacer ajustes manuales en el stock general'), ('manage_stock_repuestos', 'Puede registrar entradas y salidas en el stock de repuestos (service)'), ('manage_stock_minimo', 'Puede configurar el stock mínimo de alerta por producto')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cantidad__gt', 0), ('tipo', 'entrada')), models.Q(('cantidad__lt', 0), ('tipo', 'salida')), models.Q(('cantidad__gt', 0), ('tipo', 'devolucion')), ('tipo', 'ajuste'), _connector='OR'), name='movimientostock_signo_coherente_con_tipo'), models.CheckConstraint(condition=models.Q(('requiere_devolucion', False), models.Q(('deposito', 'repuestos'), ('tipo', 'salida')), _connector='OR'), name='movimientostock_requiere_devolucion_solo_en_salida_repuestos'), models.CheckConstraint(condition=models.Q(('salida_relacionada__isnull', True), ('tipo', 'devolucion'), _connector='OR'), name='movimientostock_salida_relacionada_solo_en_devolucion')],
            },
        ),
    ]
