# Generated by Django 5.2.17 on 2026-08-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_materialtrabajo_materialtrabajo_producto_xor_descripcion_manual'),
        ('stock', '0003_asignar_permisos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='material_trabajo',
            field=models.ForeignKey(blank=True, help_text='Línea puntual del listado de materiales que originó este movimiento. SET_NULL (no PROTECT): si la línea se borra después, el movimiento ya hecho no se pierde, solo pierde el puntero fino a esa línea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='jobs.materialtrabajo'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='jobs.trabajo'),
        ),
    ]
