# Generated by Django 5.2.17 on 2026-08-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_asignar_permisos_roles'),
        ('stock', '0004_movimientostock_material_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='linea_orden_compra',
            field=models.ForeignKey(blank=True, help_text='Línea puntual de la orden que originó esta recepción (mismo criterio que material_trabajo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='purchasing.lineaordencompra'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='purchasing.ordendecompra'),
        ),
    ]
