# Generated by Django 5.2.17 on 2026-08-26 12:19

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

CREAR_SECUENCIA_SQL = "CREATE SEQUENCE quotes_presupuesto_numero_seq;"
ELIMINAR_SECUENCIA_SQL = "DROP SEQUENCE IF EXISTS quotes_presupuesto_numero_seq;"

VINCULAR_SECUENCIA_SQL = (
    "ALTER SEQUENCE quotes_presupuesto_numero_seq "
    "OWNED BY quotes_presupuesto.numero;"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_categoria_margen_marca_margen_producto_margen'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('predeterminada', models.BooleanField(default=False, help_text='Se precarga automáticamente al crear un presupuesto nuevo.')),
                ('activa', models.BooleanField(default=True, help_text='Una plantilla inactiva no se ofrece para presupuestos nuevos, pero no se borra (conserva el histórico de los presupuestos que ya la usaron).')),
            ],
            options={
                'verbose_name': 'Plantilla de condiciones',
                'verbose_name_plural': 'Plantillas de condiciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunSQL(sql=CREAR_SECUENCIA_SQL, reverse_sql=ELIMINAR_SECUENCIA_SQL),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('quotes_presupuesto_numero_seq')", []), editable=False, unique=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de la obra para este presupuesto puntual.', max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('cantidad_unidades', models.PositiveIntegerField(default=1, help_text='Para multiplicar el total cuando se cotiza por unidad habitacional.')),
                ('descuento_general_tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], default='porcentaje', max_length=20)),
                ('descuento_general_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas_generales', models.TextField(blank=True)),
                ('condiciones', models.TextField(blank=True, help_text='Copiado desde la plantilla al crear el presupuesto; a partir de ahí es propio de este presupuesto.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='clients.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('plantilla_condiciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='quotes.plantillacondiciones')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-numero'],
            },
        ),
        migrations.RunSQL(sql=VINCULAR_SECUENCIA_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='SeccionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='quotes.presupuesto')),
            ],
            options={
                'verbose_name': 'Sección de presupuesto',
                'verbose_name_plural': 'Secciones de presupuesto',
                'ordering': ['presupuesto_id', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, help_text='Para conceptos sin producto de catálogo (ej. mano de obra/instalación).', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Congelado al crear el ítem: no cambia si después cambian los precios del catálogo.', max_digits=12)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo_iva', models.CharField(choices=[('incluido', 'IVA incluido'), ('mas_iva', '+ IVA')], default='incluido', max_length=20)),
                ('opcional', models.BooleanField(default=False, help_text="Ítem alternativo tipo 'mejora recomendada': no suma al total salvo que además esté incluido.")),
                ('incluido', models.BooleanField(default=True, help_text='Si un ítem opcional está desmarcado acá, no suma al total.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_presupuesto', to='catalog.producto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.presupuesto')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.seccionpresupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'ordering': ['presupuesto_id', 'seccion_id', 'orden'],
                'constraints': [models.CheckConstraint(condition=models.Q(('opcional', True), ('incluido', True), _connector='OR'), name='item_no_opcional_y_no_incluido')],
            },
        ),
    ]
