# Generated by Django 5.2.17 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_asignar_permisos_roles'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plantillacondiciones',
            constraint=models.UniqueConstraint(condition=models.Q(('predeterminada', True)), fields=('predeterminada',), name='una_sola_plantilla_predeterminada'),
        ),
    ]
