# Generated by Django 5.2.17 on 2026-08-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_plantillacondiciones_una_sola_plantilla_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuesto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Costo congelado al crear el ítem (mismo criterio que precio_unitario). En ítems de catálogo sale del costo vigente del proveedor elegido; en conceptos manuales es opcional y editable (para 'Mano de obra' se puede sugerir a partir de pricing.ConfiguracionGeneral.margen_mano_obra, ver apps.quotes.services.sugerir_costo_mano_obra). Sin costo cargado, el ítem queda fuera del chequeo de margen bajo.", max_digits=12, null=True),
        ),
    ]
