# Generated by Django 5.2.17 on 2026-08-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categoria_margen_marca_margen_producto_margen'),
        ('quotes', '0004_itempresupuesto_costo_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-numero'], 'permissions': [('revert_presupuesto_aceptado', 'Puede revertir un presupuesto Aceptado (volverlo a Cancelado)')], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='producto_proveedor',
            field=models.ForeignKey(blank=True, help_text="Proveedor puntual usado para fijar precio_unitario/costo_unitario. Se guarda para que 'duplicar y recalcular' pueda refrescar el costo desde ESE proveedor sin auto-elegir uno nuevo (regla de negocio 2).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_presupuesto', to='catalog.productoproveedor'),
        ),
    ]
