# Generated by Django 5.2.17 on 2026-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producto_stock_minimo_general_and_more'),
        ('quotes', '0007_asignar_permiso_revertir_aceptado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itempresupuesto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('descripcion_manual', ''), ('producto__isnull', False)), models.Q(('descripcion_manual__gt', ''), ('producto__isnull', True)), _connector='OR'), name='itempresupuesto_producto_xor_descripcion_manual'),
        ),
    ]
