# Generated by Django 5.2.17 on 2026-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reporte_comercial', 'Puede ver el reporte comercial'), ('view_montos_confidenciales', 'Puede ver montos agregados de facturación/ingresos en los reportes')],
                'default_permissions': (),
            },
        ),
    ]
