# Generated by Django 5.2.17 on 2026-08-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_asignar_permisos_rentabilidad_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportes',
            options={'default_permissions': (), 'permissions': [('view_reporte_comercial', 'Puede ver el reporte comercial'), ('view_montos_confidenciales', 'Puede ver montos agregados de facturación/ingresos en los reportes'), ('view_reporte_rentabilidad', 'Puede ver el reporte de rentabilidad'), ('view_reporte_stock', 'Puede ver el reporte de stock'), ('view_reporte_clientes', 'Puede ver el reporte de clientes'), ('view_reporte_empleados', 'Puede ver el reporte de empleados')]},
        ),
    ]
