# Generated by Django 5.2.17 on 2026-08-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('razon_social', models.CharField(blank=True, max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código oficial del fabricante/marca. No se inventa un código propio de ARQCLIMA.', max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('m2', 'Metro cuadrado'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('rollo', 'Rollo'), ('par', 'Par'), ('kit', 'Kit')], default='unidad', max_length=20)),
                ('es_repuesto', models.BooleanField(default=False, help_text='También forma parte de la línea de repuestos de service.')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalog.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['marca__nombre', 'codigo'],
                'permissions': [('manage_repuestos', 'Puede crear y editar productos de la línea de repuestos')],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoproveedor_set', to='catalog.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoproveedor_set', to='catalog.proveedor')),
            ],
            options={
                'verbose_name': 'Producto de proveedor',
                'verbose_name_plural': 'Productos por proveedor',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', through='catalog.ProductoProveedor', to='catalog.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='producto_proveedor_unico'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('marca', 'codigo'), name='producto_unico_por_marca_codigo'),
        ),
    ]
