# Generated by Django 5.2.17 on 2026-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_asignar_permisos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='margen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen (%) para productos de esta categoría. Vacío = usar el general.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='margen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen (%) para todos los productos de esta marca. Vacío = usar el general.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen (%) propio de este producto. Vacío = usar el de su marca, categoría o el general (en ese orden). Se edita aparte del resto del producto: es exclusivo de Diego, aunque Gabriel pueda editar el resto de los datos de un producto de su línea.', max_digits=5, null=True),
        ),
    ]
