# Generated by Django 5.2.17 on 2026-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categoria_margen_marca_margen_producto_margen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo_general',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Umbral de alerta de stock general (obra). Vacío = sin alerta configurada. Exclusivo de Diego (Etapa 7).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo_repuestos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Umbral de alerta de stock de repuestos (service). Vacío = sin alerta configurada. Exclusivo de Diego (Etapa 7).', max_digits=12, null=True),
        ),
    ]
