# Generated by Django 5.2.17 on 2026-08-25 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_categoria_margen_marca_margen_producto_margen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/')),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmar'), ('confirmada', 'Confirmada'), ('descartada', 'Descartada')], default='pendiente', max_length=20)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_cargadas', to=settings.AUTH_USER_MODEL)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='catalog.proveedor')),
            ],
            options={
                'verbose_name': 'Importación de lista de precios',
                'verbose_name_plural': 'Importaciones de listas de precios',
                'ordering': ['-cargado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField()),
                ('marca_texto', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre_texto', models.CharField(blank=True, max_length=255)),
                ('costo_texto', models.CharField(blank=True, max_length=50)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('codigo_proveedor_texto', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(choices=[('nuevo_producto', 'Producto nuevo'), ('nuevo_vinculo', 'Nuevo vínculo con este proveedor'), ('actualiza_costo', 'Actualiza costo'), ('sin_cambios', 'Sin cambios'), ('para_revisar', 'Para revisar'), ('error', 'Error')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('incluir', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.producto')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='imports.importacionlistaprecios')),
            ],
            options={
                'verbose_name': 'Fila de importación',
                'verbose_name_plural': 'Filas de importación',
                'ordering': ['numero_fila'],
            },
        ),
    ]
