# Generated by Django 5.2.17 on 2026-08-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_validaciones_numericas'),
        ('imports', '0002_importacion_multiformato'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionlistaprecios',
            name='ia_resultado',
            field=models.JSONField(blank=True, help_text='Metadatos de las llamadas a Claude para esta importación (modelo, tokens, filas devueltas por origen). No guarda el archivo ni la API key; solo la respuesta estructurada ya parseada, para poder auditar una extracción dudosa sin volver a llamar a la API.', null=True),
        ),
        migrations.AddField(
            model_name='importacionlistaprecios',
            name='usa_ia',
            field=models.BooleanField(default=False, help_text='Se usó Claude (mapeo de columnas y/o extracción) para analizar esta importación.'),
        ),
        migrations.AlterField(
            model_name='importacionlistaprecios',
            name='tipo_archivo',
            field=models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel antiguo (.xls)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('docx', 'Word (.docx)'), ('imagen', 'Foto de lista (imagen)')], default='xlsx', max_length=10),
        ),
        migrations.CreateModel(
            name='ProveedorColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezados', models.JSONField(help_text='Encabezados crudos tal como se leyeron del archivo, para poder auditar a qué corresponde el hash.')),
                ('encabezados_hash', models.CharField(max_length=64)),
                ('mapeo', models.JSONField(help_text='Campo canónico → índice de columna (0-based), igual forma que detectar_columnas().')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_columnas_ia', to='catalog.proveedor')),
            ],
            options={
                'verbose_name': 'Mapeo de columnas (IA)',
                'verbose_name_plural': 'Mapeos de columnas (IA)',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'encabezados_hash'), name='imports_mapeo_columnas_unico_por_proveedor_hash')],
            },
        ),
    ]
