# Generated by Django 5.2.17 on 2026-08-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importacionlistaprecios_ia_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionlistaprecios',
            name='tipo_archivo',
            field=models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel antiguo (.xls)'), ('xlsm', 'Excel con macros (.xlsm)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('docx', 'Word (.docx)'), ('imagen', 'Foto de lista (imagen)')], default='xlsx', max_length=10),
        ),
    ]
