# Generated by Django 5.2.17 on 2026-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_importacionlistaprecios_tipo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionfila',
            name='moneda',
            field=models.CharField(choices=[('ars', 'Pesos (ARS)'), ('usd', 'Dólares (USD)')], default='ars', max_length=3),
        ),
    ]
